server:
  port: 9006
spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
zuul:
  routes:
    api-movie:
      path: /api-movie/**
      service-id: provider-movie
    api-user:
      path: /api-user/**
      service-id: provider-user



