logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    - classpath:mapper/custom/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.hepai.sharingspace.po  # 注意：对应实体类的路径
  type-handlers-package: com.hepai.sharingspace.mybatis.handlers
  configuration:
    cache-enabled: true

#logging:
#  config: classpath:log4j2.xml
#  level:
#    com.hepai.sharingspace.mapper: debug


pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
