logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    - classpath:mapper/custom/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.hepai.sharingspace.po  # 注意：对应实体类的路径
  type-handlers-package: com.hepai.sharingspace.mybatis.handlers
  configuration:
    cache-enabled: true

#logging:
#  config: classpath:log4j2.xml
#  level:
#    com.hepai.sharingspace.mapper: debug


pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true

redis:
  hostName: 192.168.33.12
  port: 6379
  password:
  database: 0
  timeout: 6000 # 客户端超时时间单位是毫秒 默认是2000
  maxIdle: 80 # 最大空闲数
  maxTotal: 100 # 连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
  maxWaitMillis: 1000 # 最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
  minEvictableIdleTimeMillis: 300000 # 连接的最小空闲时间 默认1800000毫秒(30分钟)
  numTestsPerEvictionRun: 100 # 每次释放连接的最大数目,默认3
  timeBetweenEvictionRunsMillis: 30000 # 逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
  testOnBorrow: false # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
  testWhileIdle: true # 在空闲时检查有效性, 默认false

spring:
  rabbitmq:
    host: 192.168.33.12
    port: 5672
    username: root
    password: root
    publisher-confirms: true
    virtual-host: /test
    listener:
      type: simple
      simple:
        concurrency: 5
        max-concurrency: 100
        acknowledge-mode: MANUAL
        default-requeue-rejected: true  # 被拒绝的消息是否放回队列
        retry:
          enabled: true
